locale: "en-US"
site_theme: "default"

title: "Alan Gregory"
title_separator: "-"
name: "Alan Gregory"
description: "Computer Science student at the University of Houston"

url: "https://bmbo123.github.io"
baseurl: ""
repository: "bmbo123/bmbo123.github.io"

author:
  avatar: "https://media.licdn.com/dms/image/v2/D5603AQFMGxWNoRUUyg/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1710634852740?e=1771459200&v=beta&t=y-YVEqnsgIuh7G8UlsYUT9gEhM0JNArsn-5SAPQQBfU"
  name: "Alan Gregory"
  bio: "Computer Science @ University of Houston"
  location: "Houston, TX"
  employer: "University of Houston"
  email: "placeholder@gmail.com"
  github: "bmbo123"
  linkedin: "thealangregory"

breadcrumbs: false
words_per_minute: 160
future: true
read_more: "disabled"

analytics:
  provider: "google-analytics-4"
  google:
    tracking_id: "G-SYHWY70ELD"

include:
  - _pages
  - files

exclude:
  - .github
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - docker-compose.yml
  - package.json*
  - README

markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n"

kramdown:
  input: GFM
  auto_ids: true
  toc_levels: 1..6

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: false
      comments: false

permalink: /:title/
timezone: Etc/UTC

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
